### ISSUE TITLE
debug info presented in logs (and cant be turn off)

### ISSUE THREAD

**Issue by TzachiGuetta** [nitaybz/homebridge-tadiran-ac#1]
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
[TadiranAC] Heard back from AC with command 8
@nitaybz

**Comment by nitaybz** [comment]
fixed in the latest version
