### ISSUE TITLE
Stopped working due to change in format with local key

### ISSUE THREAD

**Issue by yalihart** [nitaybz/homebridge-tadiran-ac#9]
I tried using the plugin but it says that my local key is not valid even though it is. 
I tried with [this plugin](https://github.com/iRayanKhan/homebridge-tuya) and it works, but it doesn't have the best support for Tadiran AC's. Can you please update the plugin to work again? 

Might help to look [here](https://github.com/iRayanKhan/homebridge-tuya/commit/f503e93bb8ceb6cbc62d7eeea9d3b38cca782e2b)

**Comment by amird1234** [comment]
@yalihart did you get it eventually?
I'm new to this plugin and I can't get the id's right. (video is private :/)

**Comment by derflerd** [comment]
i found how to fix the problem over the net and also send to nitay the fixing

for fixing all need to do to go to hombridge teminal and get inside the folder with this command:
`cd /var/lib/homebridge/node_modules/homebridge-tadiran-ac`
and edit file index.js with the command:
`nano index.js`

and scroll down to the line:
`if (!/^[0-9a-f]+$/i.test(device.key)) return this.log.error('%s, key for %s (%s), is not a valid key.', device.key.replace(/.{4}$/, '****'), d>`

and just put in the beginning 2 "//" it will need to look like this:
`//if (!/^[0-9a-f]+$/i.test(device.key)) return this.log.error('%s, key for %s (%s), is not a valid key.', device.key.replace(/.{4}$/, '****'), d>`

save the file. 
`ctrl x'
'Enter Y`
and now restart homebridge

works great

**Comment by nitaybz** [comment]
fixed in latest version
